### ISSUE TITLE
Cannot import SV VCF

### ISSUE THREAD

**Issue by edawson** [mklarqvist/tachyon#11]
I'm trying to read in a large VCF of structural variants from a public resource, but I'm receiving the following error:
```
300	22	573	Offset: 32980955-33035235 Position: 151831760-155258869 Bins: 82-21842
301	23	333	Offset: 33035235-33066063 Position: 2654318-10083699 Bins: 0-8216
tachyon: lib/containers/data_container.cpp:618: bool tachyon::yon1_dc_t::CheckUniformity(): Assertion `cumulative_position == this->data_uncompressed.size()' failed.
```

My intuition is this is due to something strange about the SVs - perhaps one that's too large? There is also no FORMAT or SAMPLE field in this VCF - would that be an issue?

Basic run info:  
htslib-1.9
```
./tachyon/tachyon import -i sv.vcf.gz -o sv.sites.yon -c 50000
Program:   tachyon-beta-0.6.0 (Tools for querying and manipulating variant call data)
Libraries: tachyon-0.6.0; OpenSSL 3.0.0-dev xx XXX xxxx; ZSTD-1.4.0; htslib 1.9
Contact: Marcus D. R. Klarqvist <mk819@cam.ac.uk>
Documentation: https://github.com/mklarqvist/tachyon
License: MIT
----------
[2019-04-19 15:12:01,351][LOG] Calling import...
````

**Comment by mklarqvist** [comment]
Thanks for reporting this @edawson . Could you link me the file in question? I will investigate. I have an idea what the problem could be.

**Comment by mklarqvist** [comment]
The problem occurs here
https://github.com/mklarqvist/tachyon/blob/master/lib/containers/data_container.cpp#L618
when the observed word size times the stride does not equal the length of the input data stream. This is a irrecoverable error as it would result in corruption and the program therefore terminates.

I cannot immediately see why this happens. I need the file in question to debug.

**Comment by edawson** [comment]
Got it - the public data is here: https://storage.googleapis.com/gnomad-public/papers/2019-sv/gnomad_v2_sv.sites.vcf.gz

Link comes from the bottom of this page: https://gnomad.broadinstitute.org/downloads
where the .tbi can also be found.

**Comment by mklarqvist** [comment]
I can reproduce this error. I am investigating.

**Comment by mklarqvist** [comment]
This has now been fixed.
